# Build stage
FROM mcr.microsoft.com/dotnet/sdk:5.0

# set working directory
WORKDIR /app

# Copy nuget to pull nuget packs from private reps
#COPY nuget.config .

# Restore
COPY src/Service/Service.csproj ./src/Service/
RUN dotnet restore src/Service/Service.csproj
COPY src/Process/Process.csproj ./src/Process/
RUN dotnet restore src/Process/Process.csproj
COPY test/Service.Test/Service.Test.csproj ./test/Service.Test/
RUN dotnet restore test/Service.Test/Service.Test.csproj

# Copy src
COPY . .

# Test
RUN dotnet test
